services:
  mongo-db:
    container_name: mongo-db
    image: docker.io/nfrastack/mongo:7
    volumes:
      - ./db:/data/db
      - ./logs:/logs
    environment:
      - TIMEZONE=America/Vancouver
    restart: always
    networks:
      - services

networks:
  services:
    external: true
