#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2025 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
SERVICE_NAME="mongo"
prepare_service single

check_container_initialized
check_service_initialized init

mongo_build_runtime_arguments

liftoff
print_start "Starting MongoDB $(mongod --version | head -n1 | awk '{print $3}')"
exec s6-setuidgid mongo mongod ${mongocmd}
